### ISSUE TITLE
Home page have a bug

### ISSUE THREAD

**Issue by Abhay2342** [Abarragan89/react-portfolio#1]
When we open your portfolio page it does not load your Homepage automatically. We need to click on the Home button manually in order to get the Home page.

![Capture](https://user-images.githubusercontent.com/73768090/169641819-91435600-2ab5-4c1b-916d-2dce690f580d.PNG)

**Comment by Abarragan89** [comment]
I am currently working on this. I Changed my react project to use routes.
The home route is not working since Github pages home route is not '/'.
Should be fixed soon.
